export alias fmc = file-manager copy
export alias fmx = file-manager cut
export alias fml = file-manager ls
export alias fmd = file-manager clear
export alias fmpc = file-manager paste copy
export alias fmpx = file-manager paste cut
export alias fmuc = file-manager undo copy
export alias fmux = file-manager undo cut
export alias fmul = file-manager undo ls
